package br.ufrn.ppgsc.backhoe.enums;

public enum MinerType {
	BUGGY_COMMIT_MINER,
	FAILED_TESTS_MINER,
	CODE_CONTRIBUTION_MINER,
	CODECOMPLEXITY_MINER,
	BUGFIX_CONTRIBUTION_MINER,
	TASK_MINER,
	UNIFIED_CONTRIBUTION_MINER
}
