package br.ufrn.ppgsc.backhoe.miner;

public enum MinerType {
	BUGGY_COMMIT_MINER,
	FAILED_TESTS_MINER,
	CODE_CONTRIBUTION_MINER,
	CODECOMPLEXITY_MINER,
	BUGFIX_CONTRIBUTION_MINER,
	TASK_MINER
}
